# Generated by Django 4.0.2 on 2022-02-21 22:56

from django.db import migrations, models

# THIS IS WRONG !!!

class Migration(migrations.Migration):

    dependencies = [
        ('rest_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='memory_info_rss',
            field=models.BigIntegerField(help_text='The non-swapped physical memory a process has used.', verbose_name='Resident Set Size'),
        ),
        migrations.AlterField(
            model_name='process',
            name='memory_info_vms',
            field=models.BigIntegerField(help_text='The total amount of virtual memory used by the process.', verbose_name='Virtual Memory Size'),
        ),
    ]
