# Generated by Django 3.2.7 on 2021-09-08 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_server', '0004_cpustatus_cpu_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpustatus',
            old_name='cpu_time_dpc_min',
            new_name='cpu_time_dpc',
        ),
        migrations.RenameField(
            model_name='cpustatus',
            old_name='cpu_time_interrupt_min',
            new_name='cpu_time_interrupt',
        ),
    ]
