# Generated by Django 3.2.7 on 2021-10-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_server', '0007_memoryusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoryusage',
            name='virtual_available',
            field=models.PositiveBigIntegerField(default=-1, help_text='the memory that can be given instantly to processes without the system going into swap.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memoryusage',
            name='virtual_total',
            field=models.PositiveBigIntegerField(default=-1, help_text='total physical memory (exclusive swap).'),
            preserve_default=False,
        ),
    ]
