# Generated by Django 3.2.7 on 2021-10-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_server', '0008_auto_20211021_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoryusage',
            name='swap_percent',
            field=models.FloatField(help_text='the percentage usage calculated as (total - available) / total * 100'),
        ),
        migrations.AlterField(
            model_name='memoryusage',
            name='virtual_active',
            field=models.PositiveBigIntegerField(default=-1, help_text='(UNIX): memory currently in use or very recently used, and so it is in RAM.'),
        ),
        migrations.AlterField(
            model_name='memoryusage',
            name='virtual_available',
            field=models.PositiveBigIntegerField(help_text='the memory that can be given instantly to processes without the system going into swap'),
        ),
        migrations.AlterField(
            model_name='memoryusage',
            name='virtual_buffers',
            field=models.PositiveBigIntegerField(default=-1, help_text='(Linux, BSD): cache for things like file system metadata.'),
        ),
        migrations.AlterField(
            model_name='memoryusage',
            name='virtual_cached',
            field=models.PositiveBigIntegerField(default=-1, help_text='(Linux, BSD): cache for various things.'),
        ),
        migrations.AlterField(
            model_name='memoryusage',
            name='virtual_inactive',
            field=models.PositiveBigIntegerField(default=-1, help_text='(UNIX): memory that is marked as not used.'),
        ),
        migrations.AlterField(
            model_name='memoryusage',
            name='virtual_shared',
            field=models.PositiveBigIntegerField(default=-1, help_text='(Linux, BSD): memory that may be simultaneously accessed by multiple processes.'),
        ),
        migrations.AlterField(
            model_name='memoryusage',
            name='virtual_slab',
            field=models.PositiveBigIntegerField(default=-1, help_text='(Linux): in-kernel data structures cache.'),
        ),
        migrations.AlterField(
            model_name='memoryusage',
            name='virtual_total',
            field=models.PositiveBigIntegerField(help_text='total physical memory (exclusive swap)'),
        ),
        migrations.AlterField(
            model_name='memoryusage',
            name='virtual_wired',
            field=models.PositiveBigIntegerField(default=-1, help_text='(BSD, macOS): memory that is marked to always stay in RAM. It is never moved to disk.'),
        ),
    ]
