# Generated by Django 3.2.7 on 2021-10-21 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_server', '0009_auto_20211021_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memoryusage',
            name='swap_percent',
        ),
    ]
