# Generated by Django 3.2.7 on 2021-10-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_server', '0017_memoryusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diskusage',
            name='free',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='diskusage',
            name='total',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='diskusage',
            name='used',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='memoryusage',
            name='swap_free',
            field=models.BigIntegerField(help_text='free swap memory in bytes'),
        ),
        migrations.AlterField(
            model_name='memoryusage',
            name='swap_sin',
            field=models.BigIntegerField(help_text='the number of bytes the system has swapped in from disk (cumulative)'),
        ),
        migrations.AlterField(
            model_name='memoryusage',
            name='swap_sout',
            field=models.BigIntegerField(help_text='the number of bytes the system has swapped out from disk (cumulative)'),
        ),
        migrations.AlterField(
            model_name='memoryusage',
            name='swap_total',
            field=models.BigIntegerField(help_text='total swap memory in bytes'),
        ),
        migrations.AlterField(
            model_name='memoryusage',
            name='swap_used',
            field=models.BigIntegerField(help_text='used swap memory in bytes'),
        ),
        migrations.AlterField(
            model_name='memoryusage',
            name='virtual_active',
            field=models.BigIntegerField(default=-1, help_text='(UNIX): memory currently in use or very recently used, and so it is in RAM.'),
        ),
        migrations.AlterField(
            model_name='memoryusage',
            name='virtual_available',
            field=models.BigIntegerField(help_text='the memory that can be given instantly to processes without the system going into swap'),
        ),
        migrations.AlterField(
            model_name='memoryusage',
            name='virtual_buffers',
            field=models.BigIntegerField(default=-1, help_text='(Linux, BSD): cache for things like file system metadata.'),
        ),
        migrations.AlterField(
            model_name='memoryusage',
            name='virtual_cached',
            field=models.BigIntegerField(default=-1, help_text='(Linux, BSD): cache for various things.'),
        ),
        migrations.AlterField(
            model_name='memoryusage',
            name='virtual_free',
            field=models.BigIntegerField(help_text='memory not being used at all (zeroed) that is readily available; note that this doesn’t reflect the actual memory available (use available instead). total - used does not necessarily match free.'),
        ),
        migrations.AlterField(
            model_name='memoryusage',
            name='virtual_inactive',
            field=models.BigIntegerField(default=-1, help_text='(UNIX): memory that is marked as not used.'),
        ),
        migrations.AlterField(
            model_name='memoryusage',
            name='virtual_shared',
            field=models.BigIntegerField(default=-1, help_text='(Linux, BSD): memory that may be simultaneously accessed by multiple processes.'),
        ),
        migrations.AlterField(
            model_name='memoryusage',
            name='virtual_slab',
            field=models.BigIntegerField(default=-1, help_text='(Linux): in-kernel data structures cache.'),
        ),
        migrations.AlterField(
            model_name='memoryusage',
            name='virtual_total',
            field=models.BigIntegerField(help_text='total physical memory (exclusive swap)'),
        ),
        migrations.AlterField(
            model_name='memoryusage',
            name='virtual_used',
            field=models.BigIntegerField(help_text='memory used, calculated differently depending on the platform and designed for informational purposes only. total - free does not necessarily match used.'),
        ),
        migrations.AlterField(
            model_name='memoryusage',
            name='virtual_wired',
            field=models.BigIntegerField(default=-1, help_text='(BSD, macOS): memory that is marked to always stay in RAM. It is never moved to disk.'),
        ),
    ]
