# Generated by Django 3.2.7 on 2021-12-30 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_server', '0019_report_retrieved_utc'),
    ]

    operations = [
        migrations.CreateModel(
            name='UfoCaptureOutputEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_filename', models.CharField(help_text='Filename of a file on the remote station. One frame at the trigger will be saved as a still image. Exclusive with PeakHold setting.', max_length=260)),
                ('peak_hold_filename', models.CharField(help_text='Filename of a file on the remote station. Automatic composite still image which contains the peak brightness of each pixel during the detection will be saved as a still image.', max_length=260)),
                ('thumbnail_filename', models.CharField(help_text='Filename of a file on the remote station. Small size jpeg image for realtime transfer.', max_length=260)),
                ('internal_thumbnail_pathname', models.CharField(help_text='Pathname of the thumbnail stored on the server.', max_length=260)),
                ('map_filename', models.CharField(help_text='Filename of a file on the remote station. *M.bmp which contains layered information of the event.', max_length=260)),
                ('clip_filename', models.CharField(help_text='Filename of a clip file on the remote station.', max_length=260)),
                ('xml_filename', models.CharField(help_text='Filename of a xml file on the remote station. ', max_length=260)),
                ('type', models.CharField(choices=[('r', 'Recording'), ('t', 'Trigger')], help_text='Type of the UFOCapture entry', max_length=1)),
                ('filename_datetime', models.DateTimeField(help_text='Datetime value derived from from UFOCapture file.', null=True)),
                ('version', models.CharField(help_text='Value of attribute "version" of ufocapture_record inside UFOCapture XML file.', max_length=20, null=True)),
                ('xml_datetime', models.DateTimeField(help_text='Datetime value from from UFOCapture XML file.', null=True)),
                ('trig', models.IntegerField(help_text='Value of attribute "trig" of ufocapture_record inside UFOCapture XML file.', null=True)),
                ('frames', models.IntegerField(help_text='Value of attribute "frames" of ufocapture_record inside UFOCapture XML file.', null=True)),
                ('lng', models.FloatField(help_text='Value of attribute "lng" of ufocapture_record inside UFOCapture XML file.', null=True)),
                ('lat', models.FloatField(help_text='Value of attribute "lat" of ufocapture_record inside UFOCapture XML file.', null=True)),
                ('alt', models.FloatField(help_text='Value of attribute "alt" of ufocapture_record inside UFOCapture XML file.', null=True)),
                ('tz', models.CharField(help_text='Value of attribute "tz" of ufocapture_record inside UFOCapture XML file.', max_length=20)),
                ('u2', models.IntegerField(help_text='Value of attribute "u2" of ufocapture_record inside UFOCapture XML file.')),
                ('cx', models.IntegerField(help_text='Value of attribute "cx" of ufocapture_record inside UFOCapture XML file.')),
                ('cy', models.IntegerField(help_text='Value of attribute "cy" of ufocapture_record inside UFOCapture XML file.')),
                ('fps', models.FloatField(help_text='Value of attribute "fps" of ufocapture_record inside UFOCapture XML file.', null=True)),
                ('head', models.IntegerField(help_text='Value of attribute "head" of ufocapture_record inside UFOCapture XML file.', null=True)),
                ('tail', models.IntegerField(help_text='Value of attribute "tail" of ufocapture_record inside UFOCapture XML file.', null=True)),
                ('diff', models.IntegerField(help_text='Value of attribute "diff" of ufocapture_record inside UFOCapture XML file.', null=True)),
                ('sipos', models.IntegerField(help_text='Value of attribute "sipos" of ufocapture_record inside UFOCapture XML file.', null=True)),
                ('sisize', models.IntegerField(help_text='Value of attribute "sisize" of ufocapture_record inside UFOCapture XML file.', null=True)),
                ('dlev', models.IntegerField(help_text='Value of attribute "dlev" of ufocapture_record inside UFOCapture XML file.', null=True)),
                ('dsize', models.IntegerField(help_text='Value of attribute "dsize" of ufocapture_record inside UFOCapture XML file.', null=True)),
                ('countrycode', models.CharField(help_text='Value of attribute "countrycode" of ufocapture_record inside UFOCapture XML file.', max_length=2, null=True)),
                ('lid', models.CharField(help_text='Value of attribute "lid" of ufocapture_record inside UFOCapture XML file.', max_length=16, null=True)),
                ('observer', models.CharField(help_text='Value of attribute "observer" of ufocapture_record inside UFOCapture XML file.', max_length=32, null=True)),
                ('sid', models.CharField(help_text='Value of attribute "sid" of ufocapture_record inside UFOCapture XML file.', max_length=16, null=True)),
                ('cam', models.CharField(help_text='Value of attribute "cam" of ufocapture_record inside UFOCapture XML file.', max_length=32, null=True)),
                ('lens', models.CharField(help_text='Value of attribute "lens" of ufocapture_record inside UFOCapture XML file.', max_length=32, null=True)),
                ('cap', models.CharField(help_text='Value of attribute "cap" of ufocapture_record inside UFOCapture XML file.', max_length=32, null=True)),
                ('comment', models.CharField(help_text='Value of attribute "comment" of ufocapture_record inside UFOCapture XML file.', max_length=64, null=True)),
                ('interlace', models.IntegerField(help_text='Value of attribute "interlace" of ufocapture_record inside UFOCapture XML file.', null=True)),
                ('bbf', models.IntegerField(help_text='Value of attribute "bbf" of ufocapture_record inside UFOCapture XML file.', null=True)),
                ('dropframe', models.IntegerField(help_text='Value of attribute "dropframe" of ufocapture_record inside UFOCapture XML file.', null=True)),
                ('fourcc', models.IntegerField(help_text='Value of attribute "fourcc" of ufocapture_record inside UFOCapture XML file.', null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_server.report')),
            ],
        ),
    ]
