# Generated by Django 3.2.7 on 2022-01-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_server', '0020_ufocaptureoutputentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ufocaptureoutputentry',
            name='type',
            field=models.CharField(choices=[('rec', 'Recording'), ('trg', 'Trigger'), ('tmp', 'Temporary')], help_text='Type of the UFOCapture entry determined from the name of a file', max_length=3),
        ),
    ]
