# Generated by Django 3.2.7 on 2022-01-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_server', '0021_alter_ufocaptureoutputentry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ufocaptureoutputentry',
            name='cap',
            field=models.CharField(blank=True, help_text='Value of attribute "cap" of ufocapture_record inside UFOCapture XML file.', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='ufocaptureoutputentry',
            name='clip_filename',
            field=models.CharField(blank=True, help_text='Filename of a clip file on the remote station.', max_length=260, null=True),
        ),
        migrations.AlterField(
            model_name='ufocaptureoutputentry',
            name='comment',
            field=models.CharField(blank=True, help_text='Value of attribute "comment" of ufocapture_record inside UFOCapture XML file.', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='ufocaptureoutputentry',
            name='countrycode',
            field=models.CharField(blank=True, help_text='Value of attribute "countrycode" of ufocapture_record inside UFOCapture XML file.', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='ufocaptureoutputentry',
            name='fourcc',
            field=models.CharField(blank=True, help_text='Value of attribute "fourcc" of ufocapture_record inside UFOCapture XML file.', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='ufocaptureoutputentry',
            name='internal_thumbnail_pathname',
            field=models.CharField(blank=True, help_text='Pathname of the thumbnail stored on the server.', max_length=260, null=True),
        ),
        migrations.AlterField(
            model_name='ufocaptureoutputentry',
            name='lens',
            field=models.CharField(blank=True, help_text='Value of attribute "lens" of ufocapture_record inside UFOCapture XML file.', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='ufocaptureoutputentry',
            name='lid',
            field=models.CharField(blank=True, help_text='Value of attribute "lid" of ufocapture_record inside UFOCapture XML file.', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='ufocaptureoutputentry',
            name='map_filename',
            field=models.CharField(blank=True, help_text='Filename of a file on the remote station. *M.bmp which contains layered information of the event.', max_length=260, null=True),
        ),
        migrations.AlterField(
            model_name='ufocaptureoutputentry',
            name='observer',
            field=models.CharField(blank=True, help_text='Value of attribute "observer" of ufocapture_record inside UFOCapture XML file.', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='ufocaptureoutputentry',
            name='peak_hold_filename',
            field=models.CharField(blank=True, help_text='Filename of a file on the remote station. Automatic composite still image which contains the peak brightness of each pixel during the detection will be saved as a still image.', max_length=260, null=True),
        ),
        migrations.AlterField(
            model_name='ufocaptureoutputentry',
            name='sid',
            field=models.CharField(blank=True, help_text='Value of attribute "sid" of ufocapture_record inside UFOCapture XML file.', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='ufocaptureoutputentry',
            name='snapshot_filename',
            field=models.CharField(blank=True, help_text='Filename of a file on the remote station. One frame at the trigger will be saved as a still image. Exclusive with PeakHold setting.', max_length=260, null=True),
        ),
        migrations.AlterField(
            model_name='ufocaptureoutputentry',
            name='thumbnail_filename',
            field=models.CharField(blank=True, help_text='Filename of a file on the remote station. Small size jpeg image for realtime transfer.', max_length=260, null=True),
        ),
        migrations.AlterField(
            model_name='ufocaptureoutputentry',
            name='tz',
            field=models.CharField(blank=True, help_text='Value of attribute "tz" of ufocapture_record inside UFOCapture XML file.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ufocaptureoutputentry',
            name='version',
            field=models.CharField(blank=True, help_text='Value of attribute "version" of ufocapture_record inside UFOCapture XML file.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ufocaptureoutputentry',
            name='xml_filename',
            field=models.CharField(blank=True, help_text='Filename of a xml file on the remote station. ', max_length=260, null=True),
        ),
    ]
