# Generated by Django 3.2.7 on 2022-01-04 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_server', '0023_alter_ufocaptureoutputentry_cam'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='post_utc',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0)),
            preserve_default=False,
        ),
    ]
