# Generated by Django 3.2.7 on 2022-01-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_server', '0024_report_post_utc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ufocaptureoutputentry',
            name='clip_filename',
            field=models.CharField(default='EMPTY', help_text='Filename of a clip file on the remote station.', max_length=260),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='ufocaptureoutputentry',
            unique_together={('report', 'clip_filename')},
        ),
    ]
