# Generated by Django 3.2.7 on 2022-01-04 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_server', '0028_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='station_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_server.station'),
        ),
    ]
