# Generated by Django 3.2.7 on 2022-01-07 19:37

from django.db import migrations, models
import rest_server.models.ufo_capture_output


class Migration(migrations.Migration):

    dependencies = [
        ('rest_server', '0036_remove_ufocaptureoutputentry_internal_thumbnail_pathname'),
    ]

    operations = [
        migrations.AddField(
            model_name='ufocaptureoutputentry',
            name='det_level_preview',
            field=models.ImageField(blank=True, help_text='Detected pixels the brightness of which was changed more than "Detect Lev"', null=True, upload_to=rest_server.models.ufo_capture_output.preview_image_dir_path),
        ),
        migrations.AddField(
            model_name='ufocaptureoutputentry',
            name='long_term_avg_preview',
            field=models.ImageField(blank=True, help_text='Long term averaged brightness of the pixel.', null=True, upload_to=rest_server.models.ufo_capture_output.preview_image_dir_path),
        ),
        migrations.AddField(
            model_name='ufocaptureoutputentry',
            name='peak_hold_preview',
            field=models.ImageField(blank=True, help_text='Automatic composite still image which contains the peak brightness of each pixel during the detection will be saved as a still image. Peak hold is useful in nighttime luminous event observation. Exclusive with SnapShot setting.', null=True, upload_to=rest_server.models.ufo_capture_output.preview_image_dir_path),
        ),
    ]
