# Generated by Django 4.0.2 on 2022-02-03 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_server', '0038_environmentlogupload_environmentlogmeasurement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='environmentlogupload',
            old_name='is_finished',
            new_name='is_historical',
        ),
    ]
