# Generated by Django 4.0.2 on 2022-02-18 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_server', '0042_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='cmdline',
            field=models.CharField(blank=True, help_text='The command line this process has been called with as a list of strings. ', max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='cwd',
            field=models.CharField(blank=True, help_text='The process current working directory as an absolute path.', max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='username',
            field=models.CharField(blank=True, help_text='The name of the user that owns the process. On UNIX this is calculated by using real process uid.', max_length=64, null=True),
        ),
    ]
