# Generated by Django 3.2.7 on 2021-09-06 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiskPartition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=25)),
                ('mountpoint', models.CharField(max_length=255)),
                ('fstype', models.CharField(max_length=25)),
                ('opts', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_utc', models.DateTimeField()),
                ('station', models.CharField(default='dims_0', max_length=50)),
                ('hash', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DiskUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveBigIntegerField()),
                ('used', models.PositiveBigIntegerField()),
                ('free', models.PositiveBigIntegerField()),
                ('disk_partition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_server.diskpartition')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_server.report')),
            ],
        ),
    ]
