# Generated by Django 4.0.2 on 2022-03-03 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cpustatus',
            options={'verbose_name_plural': 'cpu status records'},
        ),
        migrations.AlterModelOptions(
            name='diskusage',
            options={'verbose_name_plural': 'disk usage records'},
        ),
        migrations.AlterModelOptions(
            name='memoryusage',
            options={'verbose_name_plural': 'memory usage records'},
        ),
        migrations.AlterModelOptions(
            name='ufocaptureoutputentry',
            options={'verbose_name_plural': 'ufo capture output entries'},
        ),
    ]
