# Generated by Django 4.0.2 on 2022-03-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_server', '0002_alter_cpustatus_options_alter_diskusage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
