# Generated by Django 3.2.7 on 2021-09-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_server', '0003_cpustatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpustatus',
            name='cpu_id',
            field=models.CharField(default='all', max_length=15, verbose_name='Unique identifier of a CPU ("all" for measurements across all CPUs)'),
        ),
    ]
