# Generated by Django 3.2.7 on 2021-10-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_server', '0010_remove_memoryusage_swap_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoryusage',
            name='swap_percent',
            field=models.FloatField(default=-1.0, help_text='the percentage usage calculated as (total - available) / total * 100'),
            preserve_default=False,
        ),
    ]
