# Generated by Django 3.2.7 on 2021-10-21 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_server', '0011_memoryusage_swap_percent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MemoryUsage',
        ),
    ]
