# Generated by Django 3.2.7 on 2021-10-21 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_server', '0015_memoryusage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MemoryUsage',
        ),
    ]
