# Generated by Django 3.2.7 on 2022-01-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_server', '0025_auto_20220104_1241'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ufocaptureoutputentry',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='ufocaptureoutputentry',
            constraint=models.UniqueConstraint(fields=('report', 'clip_filename'), name='name of constraint'),
        ),
    ]
