# Generated by Django 3.2.7 on 2022-01-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_server', '0026_auto_20220104_1311'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ufocaptureoutputentry',
            name='name of constraint',
        ),
        migrations.AddConstraint(
            model_name='ufocaptureoutputentry',
            constraint=models.UniqueConstraint(fields=('report', 'clip_filename'), name='unique_pair_report_clip'),
        ),
    ]
