# Generated by Django 3.2.7 on 2022-01-04 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_server', '0029_report_station_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='station',
        ),
    ]
