# Generated by Django 3.2.7 on 2022-01-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_server', '0033_alter_ufocaptureoutputentry_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='fully_processed',
            field=models.BooleanField(default=False),
        ),
    ]
