# Generated by Django 3.2.7 on 2022-01-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_server', '0034_report_fully_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='integrity_errors',
            field=models.JSONField(null=True),
        ),
    ]
