# Generated by Django 3.2.7 on 2022-01-07 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_server', '0035_report_integrity_errors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ufocaptureoutputentry',
            name='internal_thumbnail_pathname',
        ),
    ]
