# Generated by Django 4.0.2 on 2022-02-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentlogmeasurement',
            name='brightness',
            field=models.FloatField(help_text='Brightness from CdS sensor. Value of column "brightness" inside the Arduino data log file (EnvData).'),
        ),
        migrations.AlterField(
            model_name='environmentlogmeasurement',
            name='humidity_in',
            field=models.FloatField(help_text='Value of column "humidity_in" inside the Arduino data log file (EnvData). Unit: Percent.'),
        ),
        migrations.AlterField(
            model_name='environmentlogmeasurement',
            name='humidity_out',
            field=models.FloatField(help_text='Value of column "humidity_out" inside the Arduino data log file (EnvData). Unit: Percent.'),
        ),
        migrations.AlterField(
            model_name='environmentlogmeasurement',
            name='pressure_in',
            field=models.FloatField(help_text='Value of column "pressure_in" inside the Arduino data log file (EnvData). Unit: hPa.'),
        ),
        migrations.AlterField(
            model_name='environmentlogmeasurement',
            name='pressure_out',
            field=models.FloatField(help_text='Value of column "pressure_out" inside the Arduino data log file (EnvData). Unit: hPa.'),
        ),
        migrations.AlterField(
            model_name='environmentlogmeasurement',
            name='temperature_in',
            field=models.FloatField(help_text='Value of column "temperature_in" inside the Arduino data log file (EnvData). Unit: degrees of Celsius.'),
        ),
        migrations.AlterField(
            model_name='environmentlogmeasurement',
            name='temperature_out',
            field=models.FloatField(help_text='Value of column "temperature_out" inside the Arduino data log file (EnvData). Unit: degrees of Celsius.'),
        ),
        migrations.AlterField(
            model_name='process',
            name='memory_info_rss',
            field=models.BigIntegerField(help_text='The non-swapped physical memory a process has used.', verbose_name='Resident Set Size'),
        ),
        migrations.AlterField(
            model_name='process',
            name='memory_info_vms',
            field=models.BigIntegerField(help_text='The total amount of virtual memory used by the process.', verbose_name='Virtual Memory Size'),
        ),
    ]
